version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/go-node"
    schedule:
      interval: "daily"